FilmProj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', namespace="user")),
]

user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/(?P<username>[a-zA-Z]*)', views.login, name='login'),
    url(r'^create/', views.create, name='create'),
]

user/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)

    def create_location(self):
        location = self.create()
        return location

class Person(models.Model):
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    location = models.ForeignKey(Location)

    def create_person(self):
        person = self.create()
        return person

class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    person = models.ForeignKey(Person)

    def create_user(self):
        user = self.create_user()
        return user

    def create_user(self, username, password, person):
        user = self.create(username=username,password=password,person=person)
        return user

    def autheticate_user(username, password):
        result = 0
        try:
            user = User.objects.get(username=username);
            result = password == user.password
        except:
            result = 0
        return result

user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User, Person, Location

class LoginForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ('username','password')

	def __init__(self, *args, **kwargs):
		return super(LoginForm, self).__init__(*args, **kwargs)

class CreateForm(forms.ModelForm):

	class Meta:
		model = User
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		return super(CreateForm, self).__init__(*args, **kwargs)

user/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django import forms

from .models import User, Person, Location
from .forms import LoginForm

# Create your views here.

def index(request):
    latest_user = User.objects.order_by('username')[:1]
    context = {'latest_user': latest_user}
    #return HttpResponse("Here are some users.")
    return render(request, 'index.html', context)

def login(request, username):
    return HttpResponse("Login Page %s."
                        % username)

def create(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			user = form.save(commit=0)
			if User.autheticate_user(user.username, user.password):
				return HttpResponse("YES")
			else:
				return HttpResponse("NO")
		else:
			return HttpResponse("BAD FORM")
	else:
		form = LoginForm()
		return render(request, 'create_model_form.html',{'form':form})

templates/close_body.html
</body>

templates/close_head.html
</head>

templates/close_html.html
</html>

templates/open_body.html
<body>

templates/open_head.html
<head>

templates/open_html.html
<html>

user/templates/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <form action="{% url  'user:create' %}" method="post">
            
            <input type="submit" value="Create User" />
        </form>
    </body>
</html>
asdsadsad

user/templates/create_model_form.html
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  <ul>
    {{form.as_ul}}
  </ul>
  <input type="submit" value="Save" />
</form>

user/templates/index.html
<div>
    {% if latest_user %}
        <ul>
            {% for user in latest_user %}
                    <li>
                        <a href="/user/{{ user.id }}"/>
                    </li>
            {% endfor %}
        </ul>
    {% else %}
        NOPE
    {% endif %}
</div>